-- ============================================================
-- SMART OFFICE
-- Source OLTP Database
-- File: 02_create_tables.sql
-- ============================================================


-- ============================================================
-- 1. OFFICE DOMAIN
-- ============================================================

CREATE TABLE office.offices (
    office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    office_code VARCHAR(50) NOT NULL UNIQUE,
    office_name VARCHAR(255) NOT NULL,

    city VARCHAR(100) NOT NULL,
    address VARCHAR(500),
    timezone VARCHAR(100) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',

    capacity INTEGER NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_office_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_office_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


-- ============================================================
-- 2. HR DOMAIN
-- ============================================================

CREATE TABLE hr.departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_code VARCHAR(50) NOT NULL UNIQUE,
    department_name VARCHAR(255) NOT NULL,

    -- FK to employees will be added later because:
    -- employees also references departments.
    manager_id BIGINT,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_department_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE TABLE hr.positions (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    position_code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    level VARCHAR(50),

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_position_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE TABLE hr.employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_code VARCHAR(50) NOT NULL UNIQUE,

    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),

    department_id BIGINT,
    position_id BIGINT,
    office_id BIGINT,

    manager_id BIGINT,

    hire_date DATE NOT NULL,
    termination_date DATE,

    employment_type VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES hr.departments(department_id),

    CONSTRAINT fk_employee_position
        FOREIGN KEY (position_id)
        REFERENCES hr.positions(position_id),

    CONSTRAINT fk_employee_office
        FOREIGN KEY (office_id)
        REFERENCES office.offices(office_id),

    CONSTRAINT fk_employee_manager
        FOREIGN KEY (manager_id)
        REFERENCES hr.employees(employee_id),

    CONSTRAINT chk_employee_employment_type
        CHECK (
            employment_type IN (
                'FULL_TIME',
                'PART_TIME',
                'CONTRACT',
                'INTERN'
            )
        ),

    CONSTRAINT chk_employee_status
        CHECK (
            status IN (
                'ACTIVE',
                'ON_LEAVE',
                'INACTIVE',
                'TERMINATED'
            )
        ),

    CONSTRAINT chk_employee_termination_date
        CHECK (
            termination_date IS NULL
            OR termination_date >= hire_date
        )
);


-- Circular relationship is resolved after employees exists.
ALTER TABLE hr.departments
ADD CONSTRAINT fk_department_manager
FOREIGN KEY (manager_id)
REFERENCES hr.employees(employee_id);


-- ============================================================
-- 3. ACCESS CONTROL DOMAIN
-- ============================================================

CREATE TABLE access.doors (
    door_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    door_code VARCHAR(50) NOT NULL UNIQUE,
    door_name VARCHAR(255) NOT NULL,

    office_id BIGINT NOT NULL,

    floor VARCHAR(50),
    zone VARCHAR(100),

    door_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_door_office
        FOREIGN KEY (office_id)
        REFERENCES office.offices(office_id),

    CONSTRAINT chk_door_type
        CHECK (
            door_type IN (
                'ENTRY',
                'EXIT',
                'ROOM',
                'RESTRICTED'
            )
        ),

    CONSTRAINT chk_door_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE TABLE access.access_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    door_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,

    event_time TIMESTAMPTZ NOT NULL,

    access_type VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_access_event_door
        FOREIGN KEY (door_id)
        REFERENCES access.doors(door_id),

    CONSTRAINT fk_access_event_employee
        FOREIGN KEY (employee_id)
        REFERENCES hr.employees(employee_id),

    CONSTRAINT chk_access_type
        CHECK (access_type IN ('IN', 'OUT')),

    CONSTRAINT chk_access_status
        CHECK (status IN ('SUCCESS', 'DENIED'))
);


-- ============================================================
-- 4. MEETING DOMAIN
-- ============================================================

CREATE TABLE meeting.rooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    room_code VARCHAR(50) NOT NULL UNIQUE,
    room_name VARCHAR(255) NOT NULL,

    office_id BIGINT NOT NULL,

    floor VARCHAR(50),
    capacity INTEGER NOT NULL,

    has_projector BOOLEAN NOT NULL DEFAULT FALSE,
    has_video_conference BOOLEAN NOT NULL DEFAULT FALSE,
    has_whiteboard BOOLEAN NOT NULL DEFAULT FALSE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_room_office
        FOREIGN KEY (office_id)
        REFERENCES office.offices(office_id),

    CONSTRAINT chk_room_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_room_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'MAINTENANCE'
            )
        )
);


CREATE TABLE meeting.bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    room_id BIGINT NOT NULL,
    organizer_id BIGINT NOT NULL,

    title VARCHAR(255),

    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,

    attendee_count INTEGER NOT NULL DEFAULT 1,

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_booking_room
        FOREIGN KEY (room_id)
        REFERENCES meeting.rooms(room_id),

    CONSTRAINT fk_booking_organizer
        FOREIGN KEY (organizer_id)
        REFERENCES hr.employees(employee_id),

    CONSTRAINT chk_booking_time
        CHECK (end_time > start_time),

    CONSTRAINT chk_booking_attendee_count
        CHECK (attendee_count >= 1),

    CONSTRAINT chk_booking_status
        CHECK (
            status IN (
                'PENDING',
                'CONFIRMED',
                'COMPLETED',
                'CANCELLED',
                'NO_SHOW'
            )
        )
);


-- ============================================================
-- 5. DIGITAL SIGNING DOMAIN
-- ============================================================

CREATE TABLE signing.documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    document_code VARCHAR(100) NOT NULL UNIQUE,

    title VARCHAR(500) NOT NULL,
    document_type VARCHAR(50) NOT NULL,

    creator_id BIGINT NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_document_creator
        FOREIGN KEY (creator_id)
        REFERENCES hr.employees(employee_id),

    CONSTRAINT chk_document_type
        CHECK (
            document_type IN (
                'CONTRACT',
                'PURCHASE_ORDER',
                'INTERNAL_REQUEST',
                'HR_DOCUMENT',
                'POLICY'
            )
        ),

    CONSTRAINT chk_document_status
        CHECK (
            status IN (
                'DRAFT',
                'PENDING_SIGNATURE',
                'COMPLETED',
                'REJECTED',
                'CANCELLED'
            )
        )
);


CREATE TABLE signing.signing_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    document_id BIGINT NOT NULL,

    requester_id BIGINT NOT NULL,
    signer_id BIGINT NOT NULL,

    signing_order INTEGER NOT NULL DEFAULT 1,

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    signed_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_signing_request_document
        FOREIGN KEY (document_id)
        REFERENCES signing.documents(document_id),

    CONSTRAINT fk_signing_request_requester
        FOREIGN KEY (requester_id)
        REFERENCES hr.employees(employee_id),

    CONSTRAINT fk_signing_request_signer
        FOREIGN KEY (signer_id)
        REFERENCES hr.employees(employee_id),

    CONSTRAINT chk_signing_order
        CHECK (signing_order > 0),

    CONSTRAINT chk_signing_request_status
        CHECK (
            status IN (
                'PENDING',
                'SIGNED',
                'REJECTED',
                'CANCELLED',
                'EXPIRED'
            )
        ),

    CONSTRAINT chk_signed_at
        CHECK (
            signed_at IS NULL
            OR signed_at >= requested_at
        ),

    CONSTRAINT chk_rejected_at
        CHECK (
            rejected_at IS NULL
            OR rejected_at >= requested_at
        )
);


-- ============================================================
-- 6. IOT DOMAIN
-- ============================================================

CREATE TABLE iot.devices (
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    device_code VARCHAR(100) NOT NULL UNIQUE,
    device_name VARCHAR(255),

    device_type VARCHAR(50) NOT NULL,

    office_id BIGINT NOT NULL,
    room_id BIGINT,

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    installed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_device_office
        FOREIGN KEY (office_id)
        REFERENCES office.offices(office_id),

    CONSTRAINT fk_device_room
        FOREIGN KEY (room_id)
        REFERENCES meeting.rooms(room_id),

    CONSTRAINT chk_device_type
        CHECK (
            device_type IN (
                'TEMPERATURE_SENSOR',
                'HUMIDITY_SENSOR',
                'CO2_SENSOR',
                'OCCUPANCY_SENSOR',
                'MULTI_SENSOR'
            )
        ),

    CONSTRAINT chk_device_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'MAINTENANCE',
                'ERROR'
            )
        )
);


CREATE TABLE iot.device_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    device_id BIGINT NOT NULL,

    event_time TIMESTAMPTZ NOT NULL,

    metric_type VARCHAR(50) NOT NULL,
    metric_value NUMERIC(12, 4) NOT NULL,
    unit VARCHAR(30) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_device_event_device
        FOREIGN KEY (device_id)
        REFERENCES iot.devices(device_id),

    CONSTRAINT chk_metric_type
        CHECK (
            metric_type IN (
                'TEMPERATURE',
                'HUMIDITY',
                'CO2',
                'OCCUPANCY',
                'HEARTBEAT'
            )
        )
);

-- ============================================================
-- INDEXES
-- ============================================================


-- Employees

CREATE INDEX idx_employees_department
ON hr.employees(department_id);

CREATE INDEX idx_employees_position
ON hr.employees(position_id);

CREATE INDEX idx_employees_office
ON hr.employees(office_id);

CREATE INDEX idx_employees_manager
ON hr.employees(manager_id);


-- Departments

CREATE INDEX idx_departments_manager
ON hr.departments(manager_id);


-- Doors

CREATE INDEX idx_doors_office
ON access.doors(office_id);


-- Access events

CREATE INDEX idx_access_events_employee_time
ON access.access_events(employee_id, event_time DESC);

CREATE INDEX idx_access_events_door_time
ON access.access_events(door_id, event_time DESC);

CREATE INDEX idx_access_events_event_time
ON access.access_events(event_time);


-- Meeting rooms

CREATE INDEX idx_rooms_office
ON meeting.rooms(office_id);


-- Meeting bookings

CREATE INDEX idx_bookings_room_start_time
ON meeting.bookings(room_id, start_time);

CREATE INDEX idx_bookings_organizer
ON meeting.bookings(organizer_id);

CREATE INDEX idx_bookings_status
ON meeting.bookings(status);


-- Documents

CREATE INDEX idx_documents_creator
ON signing.documents(creator_id);

CREATE INDEX idx_documents_status
ON signing.documents(status);


-- Signing requests

CREATE INDEX idx_signing_requests_document
ON signing.signing_requests(document_id);

CREATE INDEX idx_signing_requests_signer
ON signing.signing_requests(signer_id);

CREATE INDEX idx_signing_requests_requester
ON signing.signing_requests(requester_id);

CREATE INDEX idx_signing_requests_status
ON signing.signing_requests(status);


-- Devices

CREATE INDEX idx_devices_office
ON iot.devices(office_id);

CREATE INDEX idx_devices_room
ON iot.devices(room_id);


-- Device events

CREATE INDEX idx_device_events_device_time
ON iot.device_events(device_id, event_time DESC);

CREATE INDEX idx_device_events_event_time
ON iot.device_events(event_time);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_offices_updated_at
BEFORE UPDATE ON office.offices
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_departments_updated_at
BEFORE UPDATE ON hr.departments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_positions_updated_at
BEFORE UPDATE ON hr.positions
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_employees_updated_at
BEFORE UPDATE ON hr.employees
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_doors_updated_at
BEFORE UPDATE ON access.doors
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_rooms_updated_at
BEFORE UPDATE ON meeting.rooms
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_bookings_updated_at
BEFORE UPDATE ON meeting.bookings
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_documents_updated_at
BEFORE UPDATE ON signing.documents
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_signing_requests_updated_at
BEFORE UPDATE ON signing.signing_requests
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER trg_devices_updated_at
BEFORE UPDATE ON iot.devices
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();